default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima-40033_development

test:
  <<: *default
  database: furima-40033_test

production:
  <<: *default
  database: furima-40033_production
  username: furima-40033
  password: <%= ENV["FURIMA-40033_DATABASE_PASSWORD"] %>
